### ISSUE TITLE
Help test namespace limit for existing profiles

### ISSUE THREAD

**Issue by igo95862** [igo95862/bubblejail#62]
Version 0.8.0 has been released with namespace limits service.

Because a lot of applications will fail to run with all namespaces disabled the available profiles had not been given any limits on namespaces. I would like in the next version for profiles to receive a some default namespace limits.

For example, this is a Chromium configuration that I found to work:

```toml
[namespaces_limits]
user = 4
mount = 0
pid = -1
ipc = 0
net = 1
time = 0
uts = 0
cgroup = 0
```

Generally the `lsns --tree` command should give a good overview on how the application might use namespaces internally.
